core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('analytics/', views.analytics, name='analytics'),
    path('product-chart/', views.product_chart, name='product-chart'),
    path('game/<int:quiz_id>/', views.take_quiz, name='game'),
    path('result/<int:quiz_id>/', views.result_page, name='result'),
]

gamification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views


app_name = 'user'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
]

game/models.py
from django.db import models

# 3rd party models
from ckeditor.fields import RichTextField

# user defined models
from core.models import TimeStampModel
from user.models import User


class ProductCategoryChoice(models.TextChoices):
    ELECTRONICS = 'ELECTRONICS', 'Electronics'
    FURNITURE = 'FURNITURE', 'Furniture'


class Product(TimeStampModel):
    product_category = models.CharField(
        max_length=64,
        choices=ProductCategoryChoice.choices,
        default=ProductCategoryChoice.ELECTRONICS
    )
    name = models.CharField(max_length=255)
    description = RichTextField()
    image = models.ImageField(upload_to='Product/')
    price = models.DecimalField(
        max_digits=9,
        decimal_places=2
    )
    min_price = models.DecimalField(
        max_digits=9,
        decimal_places=2
    )
    max_price = models.DecimalField(
        max_digits=9,
        decimal_places=2
    )

    def __str__(self):
        return self.name
    
    @property
    def avg_price(self):
        return (self.min_price + self.max_price) / 2


class UserResponse(TimeStampModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_response'
    )
    question = models.ManyToManyField(
        Product,
        blank=True
    )
    response = models.JSONField(
        blank=True,
        default=dict
    )
    points_calculated = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email
    
    class Meta:
        ordering = ('-id', )

game/views.py
from django.shortcuts import render

# Create your views here.

templates/analytics.html
{% extends './base.html' %}

{% block content %}
<div id="container" style="width: 75%;">
    <canvas id="product-chart" data-url="{% url 'core:product-chart' %}"></canvas>
</div>
{% endblock content %}


{% block extra_js %}
<script>

    $(function () {

      var $productChart = $("#product-chart");
      $.ajax({
        url: $productChart.data("url"),
        success: function (data) {

          var ctx = $productChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Product',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Product Bar Chart'
              }
            }
          });

        }
      });

    });

  </script>
{% endblock extra_js %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block title %}Gamification{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Font Awesome-->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Toastr -->
    <link rel="stylesheet" href="{% static 'css/toastr/toastr.min.css' %}" />
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    {% include './header.html' %}
    <div class="container-fluid mt-5">
      <div class="offset-md-2 col-md-8">
        {% block content %} {% endblock content %}
      </div>
    </div>
    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/toastr/toastr.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <!-- Custom JS -->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script>
      toastr.options = {
        closeButton: true,
        debug: true,
        newestOnTop: true,
        progressBar: true,
        positionClass: "toast-top-right",
        preventDuplicates: false,
        showDuration: "300",
        hideDuration: "1000",
        timeOut: "5000",
        extendedTimeOut: "1000",
        showEasing: "swing",
        hideEasing: "linear",
        showMethod: "fadeIn",
        hideMethod: "fadeOut",
      };
      $(function () {
        $(".toastMessage").on("click", function () {
          var name = $(this).attr("name");
          var message = $(this).text();
          if (name == "error") {
            toastr.error(message);
          } else if (name == "success") {
            toastr.success(message);
          } else if (name == "warning") {
            toastr.warning(message);
          } else if (name == "info") {
            toastr.info(message);
          }
        });
        $(".toastMessage").click();
      });
    </script>
    {% block extra_js %} {% endblock extra_js %}
  </body>
</html>

templates/game.html
{% extends './base.html' %} 

{% load static %}


{% block content %}
    <div class="container mt-2">
        <div class="row">
            <div class="offset-md-3 col-md-6">
                {% for question in page_obj %}
                <div class="card shadow mb-2">
                    <img src="{{question.image.url}}" class="card-img-top img-fluid" alt="{{question.name}}">
                    <div class="card-body">
                        <form action="." method="post" id="quiz-form">
                            {% csrf_token %}
                            <h5 class="card-title">{{question.name}}</h5>
                            <p class="card-text">{{question.description|safe}}</p>
                            <input type="hidden" name="question_id" id="question_id" value="{{question.id}}"><br/>
                            <div class="slidecontainer text-center">
                                <input type="range" min="{{question.min_price}}" max="{{question.max_price}}" value="{{question.avg_price}}" class="slider" id="myRange">
                                <p>Price: <span id="demo"></span></p>
                            </div>
                            <input class="form-control d-none" type="number" name="user_answer" id="user_answer" value="">
                            <br/>
                            <button class="btn btn-success float-right" type="submit">Submit</button>
                        </form>
                    </div>
                    <div class="pagination-btns p-2">
                        <ol class="pagination text-center">
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link btn btn-success nav-buttons" href="?page={{ page_obj.next_page_number }}" id="nextPageLink">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a href="{% url 'core:result' quiz_id=quiz_id %}"><button class="btn btn-danger nav-buttons">Finish</button></a>
                            </li>
                        {% endif %}
                        </ol>
                        Question {{page_obj.number}} of {{page_obj.paginator.num_pages}}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
<script>
    var slider = document.getElementById("myRange");
    var output = document.getElementById("demo");
    output.innerHTML = slider.value;
    
    slider.oninput = function() {
      output.innerHTML = this.value;
      $('#user_answer').val(slider.value);
    };
</script>
{% endblock extra_js %}

templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'core:home' %}">Gamification</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:home' %}">Home</a>
                    </li>
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:analytics' %}">Analytics</a>
                        </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        {% comment %} <li class="nav-item">
                            <a class="nav-link" href="#">Profile</a>
                        </li> {% endcomment %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </container>
    </nav>
</header>

templates/index.html
{% extends './base.html' %}

{% block content %}
    <div class="col-md-12">
        {% include './messages_and_errors.html' %}
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h5 class="card-title">Game Description</h5>
                        <hr/>
                        <p>
                            A game has already created for you once you logged in. You can enter to the game by clicking on the link below.
                            <br />
                            <br />
                            A card containing image of the product with name, description and price range will be shown. You will guess the 
                            resonable price of the product with price range. On resonable price you will be awarded <strong>100</strong> points each on correct 
                            prediction which can be <strong>Redeem</strong> as purchasing product.
                        </p>
                        <hr/>
                        <a href="{% url 'core:game' quiz_id=quiz_id %}"><button class="btn btn-primary float-right">Play Game</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/messages_and_errors.html
{% if messages %}
	{% for message in messages %}
		{% if message.tags == 'error' %}
			<button class="toastMessage d-none" name="danger">{{message}}</button>
		{% elif message.tags == 'success' %}
			<button class="toastMessage d-none" name="success">{{message}}</button>
		{% elif message.tags == 'warning' %}
			<button class="toastMessage d-none" name="warning">{{message}}</button>
		{% else %}
			<button class="toastMessage d-none" name="info">{{message}}</button>
		{% endif %}
	{% endfor %}
{% endif %}

templates/result.html
{% extends './base.html' %}

{% block content %}
<div class="container my-2">
    <div class="row">
        <div class="offset-md-2 col-md-8">
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="card-title"><strong>Congratulations!</strong> you have earned <strong>{{game_points}}</strong> points.</h5>
                    <hr/>
                    <p>
                        You have guessed <strong>{{correct_guess}}</strong> out of <strong>10</strong> question and have been awarded with <strong>{{game_points}}</strong> points.<br/>
                        Your total points have become <strong>{{total_points}}</strong>.
                    </p>
                    <hr/>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}